version: '3'

services:
  sqlserver:
    image: erickramoss/sql-server:2022
    container_name: sql-server
    environment:
      SA_PASSWORD: "Admin12345"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - my-network

networks:
  my-network:
    external: true

 # docker compose -f docker-compose-db.yml up -d
 # docker compose -f docker-compose-db.yml down

  #docker logs